name: CodeCoverage
on: [push, pull_request]
jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        go mod download
    - name: Run Unit tests
      run: |
        go test -covermode atomic -coverprofile=covprofile ./...
    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest
    - name: Debug
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALL_GITHUB_TOKEN }}
      run: echo $COVERALLS_TOKEN
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALL_GITHUB_TOKEN }}
      run: goveralls -coverprofile=covprofile -service=github
